---
- hosts: localhost
  connection: local

  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "devops_server"
      instance_type: t2.micro
      security_group: default
      region: us-east-2
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { image: "ami-037774efca2da0726", name: "manage-node-1" } # Update AMI ID according 
      - { image: "ami-085f9c64a9b75eed5", name: "manage-node-2" } # to your account
      - { image: "ami-085f9c64a9b75eed5", name: "manage-node-3" }
